version: '3.7'

services:
  frontend:
    build: .
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - enviroments.env
    volumes:
      - ./data:/app/data