export const portfolioSummary = {
    totalValue: 24680.42,
    dailyChange: 3.7,
    weeklyChange: -2.1,
    monthlyChange: 15.4,
  };
  export const cryptoAssets = [
    {
      id: 'bitcoin',
      name: 'Bitcoin',
      symbol: 'BTC',
      amount: 0.42,
      value: 12600,
      price: 30000,
      change24h: 4.2,
      color: '#F7931A',
    },
    {
      id: 'ethereum',
      name: 'Ethereum',
      symbol: 'ETH',
      amount: 3.5,
      value: 6300,
      price: 1800,
      change24h: 2.8,
      color: '#627EEA',
    },
    {
      id: 'cardano',
      name: 'Cardano',
      symbol: 'ADA',
      amount: 2800,
      value: 1400,
      price: 0.5,
      change24h: -1.2,
      color: '#0033AD',
    },
    {
      id: 'solana',
      name: 'Solana',
      symbol: 'SOL',
      amount: 45,
      value: 3200,
      price: 71.11,
      change24h: 8.4,
      color: '#00FFA3',
    },
    {
      id: 'polkadot',
      name: 'Polkadot',
      symbol: 'DOT',
      amount: 120,
      value: 960,
      price: 8,
      change24h: -0.8,
      color: '#E6007A',
    },
  ];
  export const chartData = {
    bitcoin: [
      { date: "Jan", price: 28000 },
      { date: "Feb", price: 29400 },
      { date: "Mar", price: 31200 },
      { date: "Apr", price: 27800 },
      { date: "May", price: 32500 },
      { date: "Jun", price: 29800 },
      { date: "Jul", price: 30000 },
    ],
    ethereum: [
      { date: "Jan", price: 1600 },
      { date: "Feb", price: 1750 },
      { date: "Mar", price: 1900 },
      { date: "Apr", price: 1650 },
      { date: "May", price: 1850 },
      { date: "Jun", price: 1700 },
      { date: "Jul", price: 1800 },
    ],
    cardano: [
      { date: "Jan", price: 0.48 },
      { date: "Feb", price: 0.55 },
      { date: "Mar", price: 0.52 },
      { date: "Apr", price: 0.45 },
      { date: "May", price: 0.51 },
      { date: "Jun", price: 0.47 },
      { date: "Jul", price: 0.50 },
    ],
    solana: [
      { date: "Jan", price: 52 },
      { date: "Feb", price: 58 },
      { date: "Mar", price: 65 },
      { date: "Apr", price: 59 },
      { date: "May", price: 68 },
      { date: "Jun", price: 63 },
      { date: "Jul", price: 71 },
    ],
    polkadot: [
      { date: "Jan", price: 7.2 },
      { date: "Feb", price: 7.8 },
      { date: "Mar", price: 8.5 },
      { date: "Apr", price: 7.5 },
      { date: "May", price: 8.2 },
      { date: "Jun", price: 7.6 },
      { date: "Jul", price: 8.0 },
    ],
  };
  export const performanceData = [
    { period: '24h', return: 3.7 },
    { period: '7d', return: -2.1 },
    { period: '30d', return: 15.4 },
    { period: '90d', return: 24.8 },
    { period: 'YTD', return: 32.6 },
    { period: '1y', return: 41.2 },
  ];
  export const allocationData = [
    { name: 'Bitcoin', value: 51, color: '#F7931A' },
    { name: 'Ethereum', value: 25.5, color: '#627EEA' },
    { name: 'Cardano', value: 5.7, color: '#0033AD' },
    { name: 'Solana', value: 13, color: '#00FFA3' },
    { name: 'Polkadot', value: 3.9, color: '#E6007A' },
    { name: 'Others', value: 0.9, color: '#B8B8B8' },
  ];