name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 167.86.80.4 >> ~/.ssh/known_hosts

      - name: Create Enviroment
        run: |
          ssh -i ~/.ssh/id_rsa root@167.86.80.4 << 'EOF'

            if [ ! -d "/home/frontend/.git" ]; then
              echo "Repository not found."
              rm -rf /home/frontend
              mkdir /home/frontend
              git clone https://github.com/NNazem/FinHub-Web.git /home/frontend
            fi

            cd /home/frontend || exit 1

            rm -f enviroments.env
            cat > enviroments.env <<EOF_ENV
            VITE_BACKEND_URL=${{ vars.VITE_BACKEND_URL }}
      
      - name: Deploy Frontend
        run: |
          ssh -i ~/.ssh/id_rsa root@167.86.80.4 << 'EOF'

            cd /home/frontend || exit 1
            git status || exit 1
            git checkout main || exit 1
            git pull origin main || exit 1

            docker-compose down || exit 1
            docker-compose up --build -d || exit 1
          EOF